### ISSUE TITLE
'No such dataset' in klaas_split_data with current master

### ISSUE THREAD

**Issue by jebuss** [fact-project/classifier-tools#44]
Hi, 
when running klaas_split_data from the current master, I get the following error message:
 
```
klaas_split_data build/data/gamma_precuts.hdf5 build/data/gamma \
        -f 0.25 -n train_sep \
        -f 0.5 -n train_reg \
        -f 0.25 -n test \
        -i events
INFO:root:Found a total of 692836 single-telescope events in the file
INFO:root:Writing 173209 telescope-array events to: build/data/gamma_train_sep.hdf5
Traceback (most recent call last):
  File "/home/jbuss/.conda/envs/gamma/bin/klaas_split_data", line 11, in <module>
    load_entry_point('klaas', 'console_scripts', 'klaas_split_data')()
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jbuss/software/classifier-tools/klaas/scripts/split_data.py", line 111, in main
    write_data(selected_data, path, key=key, use_hp5y=not use_pandas)
  File "/home/jbuss/software/pyfact/fact/io.py", line 34, in write_data
    to_h5py(file_path, df, key=key, **kwargs)
  File "/home/jbuss/software/pyfact/fact/io.py", line 267, in to_h5py
    append_to_h5py(f, array, key=key)
  File "/home/jbuss/software/pyfact/fact/io.py", line 428, in append_to_h5py
    raise KeyError('No such dataset {}'.format(dataset))
KeyError: 'No such dataset None'
make: *** [build/data/gamma_train_reg.hdf5] Fehler 1
```

**Comment by jebuss** [comment]
Problem occurs when writing data with pandas

**Comment by MaxNoe** [comment]
No, the error is thrown in `to_h5py` so it's pyfact using h5py

**Comment by jebuss** [comment]
hmmm, but also an error if I use the pandas option

```
Traceback (most recent call last):
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/pandas/core/indexing.py", lin
e 1794, in _get_list_axis
    return self.obj._take(key, axis=axis, convert=False)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/pandas/core/generic.py", line
 2150, in _take
    verify=True)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/pandas/core/internals.py", li
ne 4250, in take
    indexer = maybe_convert_indices(indexer, n)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/pandas/core/indexing.py", lin
e 2103, in maybe_convert_indices
    raise IndexError("indices are out-of-bounds")
IndexError: indices are out-of-bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jbuss/.conda/envs/gamma/bin/klaas_split_data", line 11, in <module>
    load_entry_point('klaas', 'console_scripts', 'klaas_split_data')()
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jbuss/software/classifier-tools/klaas/scripts/split_data.py", line 118, in main
    data = data.iloc[list(set(data.index.values) - set(selected_data.index))]
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/pandas/core/indexing.py", line 1373, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/pandas/core/indexing.py", line 1819, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/home/jbuss/.conda/envs/gamma/lib/python3.5/site-packages/pandas/core/indexing.py", line 1797, in _get_list_axis
    raise IndexError("positional indexers are out-of-bounds")
IndexError: positional indexers are out-of-bounds
make: *** [build/data/gamma_train_reg.hdf5] Fehler 1
```

**Comment by jebuss** [comment]
This is wiered. split_data ends with:

`
        data = data.iloc[list(set(data.index.values) - set(selected_data.index))]

        if event_id_key:
            ids = data[event_id_key].unique()
        else:
            ids = data.index.values
`
What happends with `ids`?

**Comment by jebuss** [comment]
seems to be a problem with line:

https://github.com/fact-project/classifier-tools/blob/b27bc8abc424719bdb0f1c6c19ec129c53802b9d/klaas/scripts/split_data.py#L117
 
If I compare the arrays:
`
In [2]: len(list(set(data.index.values) - set(selected_data.index)))
Out[2]: 346418

In [3]: len(data)
Out[3]: 692836
`

**Comment by jebuss** [comment]
So the first iteration of this line destroys it and the the error appears in this block:

https://github.com/fact-project/classifier-tools/blob/b27bc8abc424719bdb0f1c6c19ec129c53802b9d/klaas/scripts/split_data.py#L107-L115

**Comment by jebuss** [comment]
I guess the cause lies somewhere here: https://github.com/fact-project/classifier-tools/commit/cbbc148bd8ee2acce411bf38c610090d995730e9

**Comment by mackaiver** [comment]
hmm. it works on the example files. I'll keep looking.
